# encoding: utf-8

begin
  require 'bones'
rescue LoadError
  abort '### Please install the "bones" gem ###'
end

ensure_in_path 'lib'
proj = 'key_diff'

Bones{
  require "#{proj}/version"
  version KeyDiff::VERSION

  # ruby_opts [''] # silence warning, too many in addressable and/or dm-core
  gem.executables ['bin/rlang_diff']

  name    proj
  url     "http://github.com/godfat/gembox"
  authors 'Lin Jen-Shin (aka godfat 真常)'
  email   'godfat (XD) godfat.org'

  history_file   'CHANGES'
   readme_file   'README'
   ignore_file   '.gitignore'
  rdoc.include   ['\w+']
}

CLEAN.include Dir['**/*.rbc']

task :default do
  Rake.application.options.show_task_pattern = /./
  Rake.application.display_tasks_and_comments
end
